# https://github.com/Kampfkarren/selene/issues/284
name: Luacheck
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck linter
        run: selene lua
        # uses: lunarmodules/luacheck@v1
        # with:
        #   args: . --globals vim --max-line-length 150
