# https://github.com/Kampfkarren/selene/issues/284
name: lintcheck
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: selene linter
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          # Github secret token
          token: ${{ secrets.GITHUB_TOKEN }}
          # selene arguments
          args: --display-style=quiet .
          # selene version
          version: 0.26.1
